### ISSUE TITLE
CodeCoverage: exclude stdlib / boost headers from coverage report?

### ISSUE THREAD

**Issue by Time0o** [bilke/cmake-modules#28]
It seems to me like there is currently no practical way to exclude e.g. all boost headers from the final coverage report, `COVERAGE_EXCLUDES` can only exclude files, not whole directories. This really clutters up the coverage report, making it essentially useless. Is there a workaround for this?

EDIT: one method that works but kind of seems like a hack is the following:
```
file(GLOB_RECURSE excludes "/usr/include/c++/*")                               
set(COVERAGE_EXCLUDES "${excludes}")   
```
I'm not sure how to do this in a platform-independant way though.

**Comment by bilke** [comment]
I haven't used it in a while but the docs state the following:

```
# 4. If you need to exclude additional directories from the report, specify them
#    using the COVERAGE_EXCLUDES variable before calling SETUP_TARGET_FOR_COVERAGE.
#    Example:
#      set(COVERAGE_EXCLUDES 'dir1/*' 'dir2/*')
```

Looks like this is already supported, have you tried it?

**Comment by Time0o** [comment]
Yes, that is essentially what I'm doing in the code sample I provided, the problem is that this does not work if a large number of files should be ignored (e.g. every file in `/usr/include/boost/**`). As this module is very useful otherwise I will try and see if I can modify the cmake code to achieve this anyways.

**Comment by dlang123** [comment]
Did you ever come up with a way to exclude them all?

**Comment by ferdnyc** [comment]
@Time0o I know this is a year and a half old already, but my PR #39 adds setting of the `lcov` `-b` (`--base-directory`) option to `${PROJECT_SOURCE_DIR}`, which then allows `LCOV_ARGS --no-external` to work correctly. Adding that to `setup_target_for_coverage_lcov()` in `CMakeLists.txt` will cause `lcov` to automatically exclude files outside of the source tree.

**Comment by lieser** [comment]
We also had problems with excluding a directory using an absolute path, and figured out a solution:
The first `/` needs to be outside of the quotes. Otherwise it will not be recognized as an absolute path, and `PROJECT_SOURCE_DIR`/`BASE_DIRECTORY` will be appended at the beginning.

E.g. use:
```cmake
SETUP_TARGET_FOR_COVERAGE_LCOV( NAME coverage EXECUTABLE ctest EXCLUDE /'usr/include/*' 'dir1/*' 'dir2/*' )
```

I think it would be good if the usage description would contain an example using absolute paths.

**Comment by ferdnyc** [comment]
> We also had problems with excluding a directory using an absolute path, and figured out a solution:
> The first `/` needs to be outside of the quotes. Otherwise it will not be recognized as an absolute path, and `PROJECT_SOURCE_DIR`/`BASE_DIRECTORY` will be appended at the beginning.
> 
> E.g. use:
> 
> ```cmake
> SETUP_TARGET_FOR_COVERAGE_LCOV( NAME coverage EXECUTABLE ctest EXCLUDE /'usr/include/*' 'dir1/*' 'dir2/*' )
> ```
> 
> I think it would be good if the usage description would contain an example using absolute paths.

...Is that experience _since_ my #39 / #41 changes went in, @lieser ? I'm surprised, I thought I'd covered all of those cases. What CMake version are you running?

Oh, also, the issue _could_ be the single quotes — AFAIK CMake's syntax doesn't treat single-quoted strings as special, so it'll just pass the quotes through as part of the variable. IOW,
|The value of this string|is this data|
|-----------------------------------|--------------|
| `"/usr/local/*"` | `/usr/local/*`|
| `'/usr/local/*'`  | `'/usr/local/*'`|
| `/'usr/local/*'`  | `/'usr/local/*'`|

...The single-quotes would then probably be stripped out when building the `COMMAND` line for the custom target, which is why the third one works. But the first version, with double-quotes, _should_ also work.

**Comment by lieser** [comment]
> Is that experience since my #39 / #41 changes went in?

Yes, it is with the latest version from master.

> What CMake version are you running?

We are using cmake version 3.16.3

lcov: LCOV version 1.14

> Oh, also, the issue could be the single quotes

Using double quotes brings other problems for us. With an added `message( "# ${LCOV_EXCLUDES}" )` after the `list(REMOVE_DUPLICATES LCOV_EXCLUDES)` we get the following behavior:

#### 1 - double quotes, leading `/` inside quote
```cmake
setup_target_for_coverage_lcov( NAME coverage EXECUTABLE ctest EXCLUDE "/usr/include/*" "deps/*" "*/tests/*" )
# /usr/include/*;/builds/libs/cryptod/deps/*;/builds/libs/cryptod/*/tests/*
```
- `/usr/include/` is not excluded
- direct sub-folder `deps/` is not excluded
- a not direct sub-folder `*/tests/*`is excluded

So `"/usr/include/*"` is correctly treated as an absolute path. But the exclude arguments are probably not passed with quotes to lcov, which causes problems. Because calling directly `lcov --remove coverage.total /usr/include/* deps/* */tests/* --output-file coverage.info` (without quotes around excludes) shows the exact same behavior.

#### 2 - single quotes, leading `/` inside quote
```cmake
setup_target_for_coverage_lcov( NAME coverage EXECUTABLE ctest EXCLUDE '/usr/include/*' 'deps/*' '*/tests/*' )
# /builds/libs/cryptod/'/usr/include/*';/builds/libs/cryptod/'deps/*';/builds/libs/cryptod/'*/tests/*'
```
- `/usr/include/` is not excluded
- direct sub-folder `deps/` is excluded
- a not direct sub-folder `*/tests/*`is excluded

#### 2 - single quotes, leading `/` outside quote
```cmake
setup_target_for_coverage_lcov( NAME coverage EXECUTABLE ctest EXCLUDE /'usr/include/*' 'deps/*' '*/tests/*' )
# /'usr/include/*';/builds/libs/cryptod/'deps/*';/builds/libs/cryptod/'*/tests/*'
```
All three excludes work.

**Comment by ferdnyc** [comment]
@lieser  
> So `"/usr/include/*"` is correctly treated as an absolute path. But the exclude arguments are probably not passed with quotes to lcov, which causes problems. 

I think you're right, that's exactly what's happening. (You can confirm by adding `VERBOSE=1`  to the `make` command line, which will show you the commands as they're run.)

Because, _clearly_ this version of the variable has the right **data** in it:

> #### 1 - double quotes, leading `/` inside quote
> ```cmake
> setup_target_for_coverage_lcov( NAME coverage EXECUTABLE ctest EXCLUDE "/usr/include/*" "deps/*" "*/tests/*" )
> # /usr/include/*;/builds/libs/cryptod/deps/*;/builds/libs/cryptod/*/tests/*
> ```
It's just a matter of getting it to `lcov`.

How about this? What if you stick a `VERBATIM` in the `add_custom_target` definition? e.g:

```patch
diff --git a/CodeCoverage.cmake b/CodeCoverage.cmake
index d6301eb..3ae5706 100644
--- a/CodeCoverage.cmake
+++ b/CodeCoverage.cmake
@@ -256,6 +256,7 @@ function(setup_target_for_coverage_lcov)
 
         WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
         DEPENDS ${Coverage_DEPENDENCIES}
+        VERBATIM # Protect arguments to commands
         COMMENT "Resetting code coverage counters to zero.\nProcessing code coverage counters and generating report."
     )
``` 

In my quick testing, that seems to correct the issue:
```console
$ make coverage VERBOSE=1
[...]
Writing data to coverage.total
Summary coverage rate:
  lines......: 48.9% (6572 of 13443 lines)
  functions..: 66.9% (2469 of 3693 functions)
  branches...: no data found
/usr/bin/lcov --gcov-tool /usr/bin/gcov --remove coverage.total "/usr/include/ffmpeg/*/*"
 --output-file coverage.info
Reading tracefile coverage.total
Removing /usr/include/ffmpeg/libavutil/rational.h
Deleted 1 files
```

**Comment by ferdnyc** [comment]
In my testing with the VERBATIM change, it _does_ actually correct things with this issue, including @Time0o 's original point.

Turns out, when `lcov`'s wildcards are properly escaped, they _are_ recursive:
```console
/usr/bin/lcov --gcov-tool /usr/bin/gcov --remove coverage.total "/usr/include/*" \
 --output-file coverage.info
Reading tracefile coverage.total
Removing /usr/include/ImageMagick-6/Magick++/Drawable.h
Removing /usr/include/ImageMagick-6/Magick++/Geometry.h
Removing /usr/include/ImageMagick-6/Magick++/Image.h
Removing /usr/include/ImageMagick-6/Magick++/STL.h
Removing /usr/include/UnitTest++/Checks.h
Removing /usr/include/UnitTest++/MemoryOutStream.h
Removing /usr/include/UnitTest++/TestSuite.h
Removing /usr/include/c++/9/bits/alloc_traits.h
Removing /usr/include/c++/9/bits/allocated_ptr.h
Removing /usr/include/c++/9/bits/allocator.h
Removing /usr/include/c++/9/bits/atomic_base.h
Removing /usr/include/c++/9/bits/basic_string.h
Removing /usr/include/c++/9/bits/basic_string.tcc
Removing /usr/include/c++/9/bits/char_traits.h
Removing /usr/include/c++/9/bits/cpp_type_traits.h
Removing /usr/include/c++/9/bits/deque.tcc
Removing /usr/include/c++/9/bits/exception.h
Removing /usr/include/c++/9/bits/ios_base.h
Removing /usr/include/c++/9/bits/list.tcc
Removing /usr/include/c++/9/bits/move.h
Removing /usr/include/c++/9/bits/predefined_ops.h
Removing /usr/include/c++/9/bits/ptr_traits.h
Removing /usr/include/c++/9/bits/range_access.h
Removing /usr/include/c++/9/bits/shared_ptr.h
Removing /usr/include/c++/9/bits/shared_ptr_base.h
Removing /usr/include/c++/9/bits/std_abs.h
Removing /usr/include/c++/9/bits/stl_algo.h
Removing /usr/include/c++/9/bits/stl_algobase.h
Removing /usr/include/c++/9/bits/stl_construct.h
Removing /usr/include/c++/9/bits/stl_deque.h
Removing /usr/include/c++/9/bits/stl_function.h
Removing /usr/include/c++/9/bits/stl_heap.h
Removing /usr/include/c++/9/bits/stl_iterator.h
Removing /usr/include/c++/9/bits/stl_iterator_base_funcs.h
Removing /usr/include/c++/9/bits/stl_iterator_base_types.h
Removing /usr/include/c++/9/bits/stl_list.h
Removing /usr/include/c++/9/bits/stl_map.h
Removing /usr/include/c++/9/bits/stl_multimap.h
Removing /usr/include/c++/9/bits/stl_pair.h
Removing /usr/include/c++/9/bits/stl_set.h
Removing /usr/include/c++/9/bits/stl_tree.h
Removing /usr/include/c++/9/bits/stl_uninitialized.h
Removing /usr/include/c++/9/bits/stl_vector.h
Removing /usr/include/c++/9/bits/vector.tcc
Removing /usr/include/c++/9/cmath
Removing /usr/include/c++/9/ext/aligned_buffer.h
Removing /usr/include/c++/9/ext/alloc_traits.h
Removing /usr/include/c++/9/ext/atomicity.h
Removing /usr/include/c++/9/ext/new_allocator.h
Removing /usr/include/c++/9/ext/string_conversions.h
Removing /usr/include/c++/9/ext/type_traits.h
Removing /usr/include/c++/9/iomanip
Removing /usr/include/c++/9/istream
Removing /usr/include/c++/9/new
Removing /usr/include/c++/9/tuple
Removing /usr/include/c++/9/typeinfo
Removing /usr/include/c++/9/x86_64-redhat-linux/bits/gthr-default.h
Removing /usr/include/ffmpeg/libavutil/rational.h
Removing /usr/include/json/value.h
Removing /usr/include/qt5/QtCore/qalgorithms.h
Removing /usr/include/qt5/QtCore/qarraydata.h
Removing /usr/include/qt5/QtCore/qatomic_cxx11.h
Removing /usr/include/qt5/QtCore/qbasicatomic.h
Removing /usr/include/qt5/QtCore/qbytearray.h
Removing /usr/include/qt5/QtCore/qchar.h
Removing /usr/include/qt5/QtCore/qcoreapplication.h
Removing /usr/include/qt5/QtCore/qcoreevent.h
Removing /usr/include/qt5/QtCore/qdir.h
Removing /usr/include/qt5/QtCore/qflags.h
Removing /usr/include/qt5/QtCore/qglobal.h
Removing /usr/include/qt5/QtCore/qlist.h
Removing /usr/include/qt5/QtCore/qnamespace.h
Removing /usr/include/qt5/QtCore/qpoint.h
Removing /usr/include/qt5/QtCore/qrect.h
Removing /usr/include/qt5/QtCore/qrefcount.h
Removing /usr/include/qt5/QtCore/qscopedpointer.h
Removing /usr/include/qt5/QtCore/qshareddata.h
Removing /usr/include/qt5/QtCore/qsize.h
Removing /usr/include/qt5/QtCore/qstring.h
Removing /usr/include/qt5/QtCore/qtextstream.h
Removing /usr/include/qt5/QtCore/qvector.h
Removing /usr/include/qt5/QtGui/qcolor.h
Removing /usr/include/qt5/QtGui/qevent.h
Removing /usr/include/qt5/QtGui/qimage.h
Removing /usr/include/qt5/QtGui/qpainter.h
Removing /usr/include/qt5/QtGui/qpalette.h
Removing /usr/include/qt5/QtGui/qrgb.h
Removing /usr/include/qt5/QtWidgets/qsizepolicy.h
Removing /usr/include/qt5/QtWidgets/qwidget.h
Removing /usr/include/zmq.hpp
Deleted 90 files
Writing data to coverage.info
Summary coverage rate:
  lines......: 44.1% (4690 of 10640 lines)
  functions..: 45.8% (525 of 1147 functions)
  branches...: no data found
```
